name: SynUI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
#    strategy:
#      matrix:
#        configuration: [ Debug, Release ]

    runs-on: windows-latest  # For a list of available runner types, refer to
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Project_Path: SynUI.sln # Replace with your solution name, i.e. MyWpfApp.sln.

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: List Files
        run: |
          tree

      - name: Get the version
        uses: dotnet/nbgv@v0.4.0
        id: nbgv
      
      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      
      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.1
      
      # Restore the application
      - name: Restore the application
        run: msbuild $env:Project_Path /t:Restore /p:Configuration=Release
      
      # Build the application
      - name: Build the application
        run: msbuild $env:Project_Path /t:Build /p:Configuration=Release
      
      # Package the application
      - name: Package the application
        run: |
          & "SynUI.Setup\bin\Release\SynUI.Setup.exe"
      
      # Upload the application
      - name: Upload artifacts (Setup)
        uses: actions/upload-artifact@v3
        with:
          name: Setup
          path: Output\setup.exe

      - name: Upload artifacts (Portable)
        uses: actions/upload-artifact@v3
        with:
          name: Portable
          path: Output\portable.zip